export const PRODUCTS = [
  {
    id: 1,
    category: 1,
    name: 'JEAN KEY CHUPIN',
    description: 'Jean ajustado color azul marino',
    tallas: '40, 41, 42, 46, 48',
    price: 4.999,
  },
  {
    id: 2,
    category: 1,
    name: 'JEAN RECTO',
    description: 'Jean suelto en la parte inferior',
    tallas: '40, 41, 42, 46',
    price: 4.999,
  },
  {
    id: 3,
    category: 2,
    name: 'CAMISA M LARGA SIN BOLSILLOS ESTAMPADA',
    description: 'Camisa con estampado floral',
    tallas: '40, 41, 42, 46',
    price: 3.999,
  },
  {
    id: 4,
    category: 2,
    name: 'CAMISA OVERSIZE ESTAMPADA',
    description: 'Camisa de seda con estampado floral blanco y negro',
    tallas: '40, 41, 42, 46',
    price: 3.999,
  },
  {
    id: 5,
    category: 3,
    name: 'VESTIDO LARGO DE JEAN CAMISERO',
    description: 'Vestido de Jean azul claro',
    tallas: '40, 41, 44, 45',
    price: 5.999,
  },
  {
    id: 6,
    category: 3,
    name: 'VESTIDO POLERA MANGA LARGA DE LANITA',
    description: 'Vestido negro de lana',
    tallas: '42, 46, 47, 48',
    price: 4.499,
  },
  {
    id: 7,
    category: 4,
    name: 'CAMPERA PUFFER ENGOMADA DOBLE CIERRE',
    description: 'Campera gruesa color negro',
    tallas: 'S',
    price: 5.999,
  },
  {
    id: 8,
    category: 4,
    name: 'CAMPERA CORTA DE JEAN',
    description: 'Campera de jean negra',
    tallas: '40, 41, 46, 47, 48, 49',
    price: 3.999,
  },
  {
    id: 9,
    category: 1,
    name: 'CHUPIN DE BENGALINA PRINCIPE DE GALES',
    description: 'Pantalon ajustado a cuadros gris y negro',
    tallas: '41, 42, 46, 48',
    price: 4.999,
  },
  {
    id: 9,
    category: 2,
    name: 'BLUSA MANGA CORTA ESTAMPADA',
    description: 'Blusa roja y amarilla con estampado floral',
    tallas: '41, 42, 46, 48',
    price: 4.999,
  },
  {
    id: 10,
    category: 3,
    name: 'VESTIDO MANGA CORTA FIBRANA CON CIERRE',
    description: 'Vestido púrpura frío',
    tallas: '43, 44, 47, 50',
    price: 2.999,
  },
  {
    id: 11,
    category: 4,
    name: 'CAMPERA INFLABLE',
    description: 'Vestido púrpura frío',
    tallas: '40, 41, 42, 45',
    price: 6.999,
  },
];
